CREATE TABLE BOARD
(
	IDX serial NOT NULL,
	PARENT_IDX NUMERIC,
	TITLE CHARACTER VARYING NOT NULL,
	CONTENTS CHARACTER VARYING NOT NULL,
	HIT_CNT NUMERIC NOT NULL,
	DEL_GB CHARACTER VARYING(1) DEFAULT 'N' NOT NULL,
	REG_DTM text DEFAULT to_char(now(), 'yyyy-mm-dd HH24:MI:SS') NOT NULL,
	REG_ID CHARACTER VARYING NOT NULL
);
COMMENT ON TABLE BOARD IS '게시판';
COMMENT ON COLUMN BOARD.IDX IS '인덱스';
COMMENT ON COLUMN BOARD.PARENT_IDX IS '부모글 인덱스';
COMMENT ON COLUMN BOARD.TITLE IS '제목';
COMMENT ON COLUMN BOARD.CONTENTS IS '내용';
COMMENT ON COLUMN BOARD.HIT_CNT IS '조회수';
COMMENT ON COLUMN BOARD.DEL_GB IS '삭제구분';
COMMENT ON COLUMN BOARD.REG_DTM IS '생성일자';
COMMENT ON COLUMN BOARD.REG_ID IS '생성자 ID';
